baseURL = "https://feed.grantcuster.com/"
languageCode = "en-us"
title = "Grant Custer â†’ Feed"
Paginate = 16

[permalinks]
  posts = "post/:filename"

[taxonomies]
  feed_type = "feed_type"

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "rss"
